[package]
name = "turing-pattern"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.14"
nannou = "0.19.0"
ndarray = "0.15.4"
ndarray-rand = "0.14.0"
rand = "0.8.5"
